//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Data : DbContext
    {
        public Data()
            : base("name=Data")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChamCong> ChamCongs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
    
        public virtual ObjectResult<Nullable<double>> sp_TinhLuong(Nullable<int> idNV, Nullable<int> thangCong)
        {
            var idNVParameter = idNV.HasValue ?
                new ObjectParameter("IdNV", idNV) :
                new ObjectParameter("IdNV", typeof(int));
    
            var thangCongParameter = thangCong.HasValue ?
                new ObjectParameter("ThangCong", thangCong) :
                new ObjectParameter("ThangCong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_TinhLuong", idNVParameter, thangCongParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TongNgayCong(Nullable<int> idNV, Nullable<int> thangCong)
        {
            var idNVParameter = idNV.HasValue ?
                new ObjectParameter("IdNV", idNV) :
                new ObjectParameter("IdNV", typeof(int));
    
            var thangCongParameter = thangCong.HasValue ?
                new ObjectParameter("ThangCong", thangCong) :
                new ObjectParameter("ThangCong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TongNgayCong", idNVParameter, thangCongParameter);
        }
    }
}
