//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhongBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongBan()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }

        [Display(Name = "Mã Phòng Ban")]
        public int IdPB { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [Display(Name = "Tên Phòng Ban")]
        public string TenPhong { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [Display(Name = "Hotline Phòng Ban")]
        public string SDT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
