//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
  
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
using (Html.BeginForm()) 
{
    

#line default
#line hidden

#line 4 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 12 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 15 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 16 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 17 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
               __o = Html.EditorFor(model => model.IsAdmin);


#line default
#line hidden

#line 18 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
               __o = Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" });


#line default
#line hidden

#line 19 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 20 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 21 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" });


#line default
#line hidden

#line 22 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 23 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 24 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" });


#line default
#line hidden

#line 25 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 26 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 27 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" });


#line default
#line hidden

#line 28 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.QueQuan, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 29 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 30 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.QueQuan, "", new { @class = "text-danger" });


#line default
#line hidden

#line 31 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.DanToc, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 32 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.DanToc, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 33 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.DanToc, "", new { @class = "text-danger" });


#line default
#line hidden

#line 34 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.ChuyenNganh, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 35 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.ChuyenNganh, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 36 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.ChuyenNganh, "", new { @class = "text-danger" });


#line default
#line hidden

#line 37 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.IdPB, "IdPB", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 38 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.DropDownList("IdPB", null, htmlAttributes: new { @class = "form-control" });


#line default
#line hidden

#line 39 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.IdPB, "", new { @class = "text-danger" });


#line default
#line hidden

#line 40 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.IdCV, "IdCV", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 41 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.DropDownList("IdCV", null, htmlAttributes: new { @class = "form-control" });


#line default
#line hidden

#line 42 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.IdCV, "", new { @class = "text-danger" });


#line default
#line hidden

#line 43 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.TrinhDoHV, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 44 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.TrinhDoHV, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 45 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.TrinhDoHV, "", new { @class = "text-danger" });


#line default
#line hidden

#line 46 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.LuongCB, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 47 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.LuongCB, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 48 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.LuongCB, "", new { @class = "text-danger" });


#line default
#line hidden

#line 49 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
          
}

#line default
#line hidden

#line 50 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\4\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
  
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
using (Html.BeginForm()) 
{
    

#line default
#line hidden

#line 4 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 12 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 15 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 16 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 17 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
               __o = Html.EditorFor(model => model.IsAdmin);


#line default
#line hidden

#line 18 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
               __o = Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" });


#line default
#line hidden

#line 19 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 20 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 21 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" });


#line default
#line hidden

#line 22 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 23 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 24 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" });


#line default
#line hidden

#line 25 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 26 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 27 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" });


#line default
#line hidden

#line 28 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.QueQuan, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 29 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 30 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.QueQuan, "", new { @class = "text-danger" });


#line default
#line hidden

#line 31 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.DanToc, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 32 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.DanToc, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 33 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.DanToc, "", new { @class = "text-danger" });


#line default
#line hidden

#line 34 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.ChuyenNganh, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 35 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.ChuyenNganh, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 36 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.ChuyenNganh, "", new { @class = "text-danger" });


#line default
#line hidden

#line 37 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.IdPB, "IdPB", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 38 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.DropDownList("IdPB", null, htmlAttributes: new { @class = "form-control" });


#line default
#line hidden

#line 39 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.IdPB, "", new { @class = "text-danger" });


#line default
#line hidden

#line 40 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.IdCV, "IdCV", htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 41 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.DropDownList("IdCV", null, htmlAttributes: new { @class = "form-control" });


#line default
#line hidden

#line 42 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.IdCV, "", new { @class = "text-danger" });


#line default
#line hidden

#line 43 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.TrinhDoHV, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 44 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.TrinhDoHV, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 45 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.TrinhDoHV, "", new { @class = "text-danger" });


#line default
#line hidden

#line 46 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
       __o = Html.LabelFor(model => model.LuongCB, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 47 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.EditorFor(model => model.LuongCB, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 48 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.LuongCB, "", new { @class = "text-danger" });


#line default
#line hidden

#line 49 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
          
}

#line default
#line hidden

#line 50 "C:\Users\ASUS\AppData\Local\Temp\0E98AC741E019D68503D515728FB28527F1C\2\QuanLyNhanSu\Views\NhanViens\Create.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
}
}
}
